// tabulated /api/utils/generatePdf.js

import PDFDocument from "pdfkit";
import getStream from "get-stream";

export async function generatePdfBuffer({
  fullName,
  birthdate,
  birthTime,
  birthPlace,
  reading = {},
}) {
  const doc = new PDFDocument({ margin: 50 });
  const chunks = [];
  doc.on("data", (chunk) => chunks.push(chunk));
  doc.on("end", () => console.log("✅ PDF generated"));

  const divider = (title) => {
    doc.fontSize(16).fillColor("#5a3ec8").text(title, { underline: true }).moveDown(0.5);
  };

  doc
    .fontSize(22)
    .fillColor("#4B0082")
    .text("✨ Spiritual Report: Ask Your Question", { align: "center" })
    .moveDown(1);

  doc.fontSize(13).fillColor("#000");
  doc.text(`👤 Name: ${fullName}`);
  doc.text(`📅 Birth Date: ${birthdate}`);
  doc.text(`⏰ Birth Time: ${birthTime}`);
  doc.text(`🌍 Birth Place: ${birthPlace}`).moveDown(1);

  divider("💫 Answer to Your Question");
  doc.fontSize(12).fillColor("#333").text(reading.answer || "No answer available.").moveDown(1);

  divider("🌞 Astrology Report");
  doc.fontSize(12).text(reading.astrology || "No astrology data available.").moveDown(0.5);
  doc.text("Significance & Key Aspects", { underline: true }).moveDown(0.3);

  const astrologyTable = [
    ["Planetary Positions", "Influence of celestial positions on personality"],
    ["Ascendant Sign", "Your outer personality and approach to life"],
    ["Astrological Houses", "Domains of life energy and experience"],
    ["Career & Work", "Influence on professional growth"],
    ["Love & Relationships", "Emotional compatibility and bonding"],
    ["Health & Wellbeing", "Vitality and self-care tendencies"],
  ];

  astrologyTable.forEach(([a, b]) => doc.text(`• ${a}: ${b}`));
  doc.moveDown(1);

  divider("🔢 Numerology Report");
  const numerologyTable = [
    ["Life Path", "Represents your life journey and purpose"],
    ["Expression", "Reveals your talents and personality"],
    ["Personality", "How others perceive you"],
    ["Soul Urge", "Your inner motivations and desires"],
    ["Maturity", "Your evolving life lessons"],
  ];
  numerologyTable.forEach(([a, b]) => doc.text(`• ${a}: ${b}`));
  doc.moveDown(1);

  divider("✋ Palmistry Report");
  const palmistryTable = [
    ["Life Line", "Vitality, stamina, and health"],
    ["Head Line", "Mental focus, decisions, and clarity"],
    ["Heart Line", "Emotions, relationships, and empathy"],
    ["Fate Line", "Career direction and life changes"],
    ["Fingers", "Traits and characteristics"],
    ["Mounts", "Potential areas of strength"],
  ];
  palmistryTable.forEach(([a, b]) => doc.text(`• ${a}: ${b}`));

  doc.moveDown(2);
  doc
    .fontSize(10)
    .fillColor("#777")
    .text("Generated by Hazcam Spiritual Systems • Powered by OpenAI", {
      align: "center",
    });

  doc.end();
  return await getStream.buffer(doc);
}
